//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGaraOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAODOANHTHU()
        {
            this.CTBAOCAODOANHTHUs = new HashSet<CTBAOCAODOANHTHU>();
        }
    
        public int MaBaoCaoDoanhThu { get; set; }
        public System.DateTime ThangBaoCao { get; set; }
        public System.DateTime NamBaoCao { get; set; }
        public decimal TongDoanhThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBAOCAODOANHTHU> CTBAOCAODOANHTHUs { get; set; }
    }
}
