//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGaraOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTON
    {
        public int MaVatTuPhuTung { get; set; }
        public System.DateTime ThangBaoCaoTon { get; set; }
        public System.DateTime NamBaoCaoTon { get; set; }
        public int TonDau { get; set; }
        public int PhatSinh { get; set; }
        public int TonCuoi { get; set; }
    
        public virtual VATTUPHUTUNG VATTUPHUTUNG { get; set; }
    }
}
