//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGaraOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SUDUNGVTPT
    {
        public int MaChiTietSuaChua { get; set; }
        public int MaVatTuPhuTung { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual CHITIETSUACHUA CHITIETSUACHUA { get; set; }
        public virtual VATTUPHUTUNG VATTUPHUTUNG { get; set; }
    }
}
