//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGaraOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public int MaNguoiDung { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string TenNguoiDung { get; set; }
        public string DiaChiNguoiDung { get; set; }
        public string SDTNguoiDung { get; set; }
        public string CCCDNguoiDung { get; set; }
        public System.DateTime NgaySinhNguoiDung { get; set; }
        public int MaNhom { get; set; }
    
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
    }
}
