//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalGaraOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUSUACHUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUSUACHUA()
        {
            this.CHITIETSUACHUAs = new HashSet<CHITIETSUACHUA>();
        }
    
        public int MaSuaChua { get; set; }
        public int MaTiepNhan { get; set; }
        public System.DateTime NgaySuaChua { get; set; }
        public Nullable<decimal> TongTienSuaCHua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSUACHUA> CHITIETSUACHUAs { get; set; }
        public virtual XE XE { get; set; }
    }
}
